### ISSUE TITLE
Error while running npm start

### ISSUE THREAD

**Issue by ghost** [floordps/Angular-Weather-App#1]
I tried to run the app, but I'm getting an error.

steps I did:

1. npm i
2. npm start

The app isn't able to load locally and I get the error below:

```
$ npm start

> angular-weather-app@0.0.0 start C:\Users\adrian.salinas\Desktop\Angular-Weather-App               Hash: 51b6a2ec3fef040097e8                                  Time: 18094ms                                                                   chunk    {0} main.bundle.js, main.bundle.map (main) 15.8 kB {3} [initial] [rendered]
chunk    {1} styles.bundle.css, styles.bundle.map, styles.bundle.map (styles) 146 kB {4} [initial] [rendered]
chunk    {2} scripts.bundle.js, scripts.bundle.map (scripts) 162 kB {4} [initial] [rendered]
chunk    {3} vendor.bundle.js, vendor.bundle.map (vendor) 3.13 MB [initial] [rendered]
chunk    {4} inline.bundle.js, inline.bundle.map (inline) 0 bytes [entry] [rendered]

ERROR in ./src/app/weather.service.ts
Module build failed: Error: C:/Users/adrian.salinas/Desktop/Angular-Weather-App/src/app/weather.service.ts (4,17): Cannot find module '../assets/weatherApiConfig'.)
    at _checkDiagnostics (C:\Users\adrian.salinas\Desktop\Angular-Weather-App\node_modules\@ngtools\webpack\src\loader.js:116:15)
    at C:\Users\adrian.salinas\Desktop\Angular-Weather-App\node_modules\@ngtools\webpack\src\loader.js:141:17
 @ ./src/app/weather-forecast/weather-forecast.component.ts 11:0-52
 @ ./src/app/weather-route/weather-route.module.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi main
webpack: bundle is now VALID.

```

**Comment by floordps** [comment]
you need create a weatherApiConfig.ts file under the assets folder.

`export default {
  key: '<api key>',
  domain: '<domain>',
  tideForecastRoute: '<routes>'
}
`
